M48
; DRILL file {KiCad 9.0.6} date 2025-12-13T17:25:43+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-13T17:25:43+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X79.18Y-33.432
X79.18Y-39.212
T2
X120.5Y-58.0
X123.5Y-58.0
M30
